---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx_conf.conf: |
    server {
      listen 8080;

      location /api/v1/movies {
        proxy_pass http://movie-app-service:8000/api/v1/movies;
      }

      location /api/v1/casts {
        proxy_pass http://cast-app-service:8000/api/v1/casts;
      }
    }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.nginx.name }}
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.nginx.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.nginx.name }}
    spec:
      containers:
      - name: {{ .Values.nginx.containerName }}
        image: {{ .Values.nginx.image }}:{{ .Values.nginx.version }}
        ports:
        - containerPort: {{ .Values.nginx.port }}
        volumeMounts:
        - mountPath: {{ .Values.nginx.volumeMountPath }}
          name: {{ .Values.nginx.volumeName }}
      volumes:
      - name: {{ .Values.nginx.volumeName }}
        configMap:
          name: nginx-configmap
          items:
          - key: nginx_conf.conf
            path: nginx_conf.conf
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}-service
  labels:
    name: {{ .Values.nginx.label }}-service
spec:
  type: NodePort
  ports:
    - port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.nginx.name }}
